services:
  postgres:
    image: postgres:16-alpine
    container_name: n8n-vps-postgres
    environment:
      - POSTGRES_DB=${DB_POSTGRESDB_DATABASE}
      - POSTGRES_USER=${DB_POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRESDB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - n8n_net
    restart: unless-stopped


  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-vps-app
    depends_on:
      - postgres
    expose:
      - "5678"
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${TZ}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_LOG_LEVEL=${N8N_LOG_LEVEL:-info}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE:-false}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_SCHEMA=${DB_POSTGRESDB_SCHEMA}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_net
    restart: unless-stopped


  nginx:
    image: nginx:1.25-alpine
    container_name: n8n-vps-nginx
    depends_on:
      - n8n
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    networks:
      - n8n_net
    restart: unless-stopped


  certbot:
    image: certbot/certbot:latest
    container_name: n8n-vps-certbot
    depends_on:
      - nginx
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email ${SSL_EMAIL} --agree-tos --no-eff-email ${CERTBOT_STAGING} -d ${DOMAIN_NAME}


volumes:
  n8n_data:
  pg_data:
  certbot-etc:
  certbot-var:
  web-root:


networks:
  n8n_net:
